# Generated by Django 5.1 on 2024-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(null=True)),
                ('messages', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
