# Generated by Django 5.1 on 2024-08-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0002_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='messages',
            new_name='message',
        ),
    ]
